name: Auto-approve Renovate
on:
  schedule:
    - cron: '1 * * * *'
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: read
  checks: read
  statuses: read
  id-token: write
jobs:
  approve:
    uses: grafana/k6-ci/.github/workflows/auto-approve-renovate.yml@777962b022a831166517639e542630d8b7d1455f # k6-ci#69 merge commit
